In [2]:
import numpy as np
np.__version__

'1.13.3'

## 從List中建立陣列

In [3]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
# NumPy限制所有在陣列中的內容需為同樣的型態。如果型態不符合，NumPy將會試著自動轉換其型態
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [5]:
# 設定陣列的資料型態
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [6]:
# 使用巢狀list 產生多維的陣列
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## 從無到有建立陣列

In [7]:
# 建立一個內容全為0，長度為10的整數陣列
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 建立一個內容全為1的 3x5 浮點數陣列
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [9]:
# 建立一個填滿 3.14 內容的 3x5 陣列
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [11]:
# 建立一個依序填滿的陣列
# 從0開始，到20結束，每次以2為間隔
# (這和內建的range()函式類似)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# 建立一個5個值的陣列，在0到1之間平均分佈
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [12]:
# 建立一個平均分佈的 3x3 陣列
# 在0到1之間亂數值
np.random.random((3, 3))

array([[ 0.1439583 ,  0.79914932,  0.55760037],
       [ 0.39539252,  0.31210475,  0.90420737],
       [ 0.74009014,  0.87580128,  0.35397777]])

In [13]:
# 建立一個 3x3 的陣列，內容為常態分佈的亂數值
# 平均是0而標準差為1
np.random.normal(0, 1, (3, 3))

array([[ 0.30559515,  0.05021874, -0.17787671],
       [ 0.4511261 ,  0.4958821 ,  1.76206083],
       [ 1.63987176, -0.39899181,  0.84456747]])

In [15]:
# 建立一個 3x3 的陣列，內容為介於範圍是[0, 10]的整數亂數
np.random.randint(0, 10, (3, 3))

array([[6, 0, 9],
       [4, 5, 0],
       [8, 6, 0]])

In [16]:
# 建立一個 3x3 的單位矩陣
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
# 建立一個3個整數的未初始化陣列
# 這些值會是原本就存在那些記憶體中的值
np.empty(3)

array([ 1.,  1.,  1.])

### NumPy的標準資料型態
* bool_ 布林值
* int_ 預設的整數型態(和 C 的 long 一樣，一般不是int64 就是int32)
* intc 和 C 的 int 一樣(一般是int32 或 int64)
* intp 用來做為索引的整數 (和 C 的 ssize_t 一樣； 一般不是 int32 就是 int64)
* int8 位元組(-128 到 127)
* int16 整數(-32768 到 32767)
* int32 整數(-2147483648 到 2147483647)
* int64 整數(-9223372036854775808 到 9223372036854775807)
* uint8 無號整數(0 到 255)
* uint16 無號整數(0 到 65535)
* uint32 無號整數(0 到 4294967295)
* uint64 無號整數(0 到 18446744073709551615)
* float_ float64的簡稱
* float16 半精度浮點數：正負號位元，5位元指數，10位元尾數
* float32 單精度浮點數：正負號位元，8位元指數，23位元尾數
* float64 倍精度浮點數：正負號，11位元指數，52位元尾數
* complex_ complex128的簡稱
* complex64 複數，使用32位元浮點數表示
* complex128 複數，使用64位元浮點數表示

In [19]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## NumPy 陣列基礎
* 陣列的屬性：決定陣列的大小、形狀、記憶體使用、以及資料型態
* 陣列的索引：取得以及設定陣列元素個別的值
* 陣列的切片：在大陣列中取得和設定其中較小的子陣列
* 陣列的重塑：改變陣列的形狀(shape)
* 陣列的組合和分割：把幾個陣列組合成1個，以及把一個陣列切割成許多個

### 陣列的屬性
